name: Request review for CI files

on:
  pull_request_target:
    types:
      - opened
    paths:
      - '.github/actions/**/*.yaml'
      - '.github/workflows/*.yaml'

permissions:
  pull-requests: write

jobs:
  request-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |-
            const reviewers = ['RadxaYuntian'];
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: reviewers
            });
